Move the ground truth closure computation to C++
PRBonn/MapClosures pull request #32
Opened 2024-08-28 13:20 UTC by saurabh1002

1. Move GT closures computation to C++ and make it fast, python equivalent takes ages for large datasets
2. Provide a standalone `gt_closure_pipeline` to generate and store ground truth closures

2024-08-28 13:27 UTC, tizianoGuadagnino commented on cpp/gt_closures/GTClosures.cpp
Put license please

2024-08-29 13:44 UTC, benemer commented
@saurabh1002 I marked this as draft because it looks like you are still working on it. Just let us know when it's ready to review :+1:

2024-10-15 12:10 UTC, benemer requested changes

2024-10-15 12:11 UTC, benemer commented
Amazing speed-up, love it :)

2024-10-15 12:27 UTC, benemer approved these changes

2024-10-15 13:10 UTC, tizianoGuadagnino commented on cpp/gt_closures/GTClosures.cpp
> +                       double voxel_size,
```suggestion
                       const double voxel_size,
```

2024-10-15 13:16 UTC, merged